import 'classlist-polyfill'
import 'babel-polyfill'

import '../scss/common.scss'
import '~/slidingnav'
import '~/alert'
import '~/scanner'
import '~/lightbox'
import '~/embed-pdf'
import '~/detect-js'
