import 'classlist-polyfill'
import 'element-dataset'
import 'babel-polyfill'

import '../sass/common.sass'
import '~/slidingnav'
import '~/alert'
import '~/scanner'
import '~/lightbox'
import '~/embed-pdf'
import '~/detect-js'
