# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 15:43
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='warning',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='A warning for sources not to submit documents via this form.'),
        ),
    ]
