# Generated by Django 2.1.7 on 2019-06-06 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_customimage_file_hash'),
        ('forms', '0002_auto_20190219_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.CustomImage'),
        ),
    ]
