repos:
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.32.0
    hooks:
      - id: django-upgrade
        args: [--target-version, '5.2']

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
        name: Enforce end of file format
        exclude: '\.svg$|\.html$|blog/static/pdf.js/build/.+\.js'

      - id: trailing-whitespace
        name: Enforce removal of trailing whitespace

      - id: mixed-line-ending
        args: [--fix=lf]

      - id: fix-byte-order-marker

      - id: check-json
      - id: check-toml
      - id: check-yaml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.7
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/oxipng/oxipng
    rev: v10.2.1
    hooks:
      - id: oxipng
        args: ['-o', '6', '--strip', 'safe']
        # Keep in sync with `png_paths` in the justfile
        files: '^common/static/images/'

  - repo: https://github.com/kytta/mirrors-svgo
    rev: v4.1.0
    hooks:
      - id: svgo
        # Keep in sync with `svg_paths` in the justfile
        files: '^common/static/images/'

  - repo: https://github.com/thibaudcolas/pre-commit-stylelint
    rev: v17.15.0
    hooks:
      - id: stylelint
        files: \.scss$
        additional_dependencies:
          - stylelint
          - stylelint-config-standard-scss

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.39.1
    hooks:
      - id: eslint
        files: \.jsx?$
        additional_dependencies:
          - eslint@9.39.5
          - '@eslint/js@9.39.5'
          - eslint-config-prettier@10.1.8
          - eslint-import-resolver-webpack@0.13.11
          - eslint-plugin-import@2.32.0
          - eslint-plugin-jsx-a11y@6.10.2
          - eslint-plugin-react@7.37.5
          - eslint-plugin-react-hooks@7.1.1
          - globals@17.12.0

  - repo: https://github.com/JoC0de/pre-commit-prettier
    rev: v3.9.6
    hooks:
      - id: prettier
        files: \.jsx?$
        additional_dependencies:
          - prettier
