---
networks:
  app:

x-variables:
  db-name: &db-name securedropdb
  db-username: &db-username securedrop
  db-password: &db-password securedroppassword

services:
  postgresql:
    image: docker.io/library/postgres:14
    init: true
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - ./:/django:ro
    environment:
      POSTGRES_PASSWORD: *db-password
      POSTGRES_USER: *db-username
      POSTGRES_DB: *db-name
    user: postgres
    healthcheck:
      test:
        [
          'CMD',
          'pg_isready',
          '-q',
          '-h',
          'localhost',
          '-U',
          *db-username,
          '--dbname',
          *db-name,
        ]
      timeout: 45s
      interval: 10s
      retries: 10
    networks:
      app:
        aliases:
          - db

  node:
    image: localhost/securedroporg-node
    build:
      context: .
      dockerfile: ci/containers/Containerfile
      target: node-dev
      args:
        USERID: ${UID:?err}
    init: true
    volumes:
      - ./:/django:z
    working_dir: /django
    user: ${UID:?err}
    healthcheck:
      test: jq '.status' build/static/bundles/webpack-stats.json |grep -q -e compiling -e error -e done
      interval: 10s
      start_period: 1m30s
    userns_mode: keep-id
    networks:
      - app

  django:
    init: true
    stdin_open: true
    tty: true
    image: localhost/securedroporg-django
    build:
      context: .
      dockerfile: ci/containers/Containerfile
      target: dev
      args:
        USERID: ${UID:?err}
    depends_on:
      postgresql:
        condition: service_healthy
      node:
        condition: service_healthy
    environment:
      DEPLOY_ENV: dev
      DJANGO_DB_HOST: db
      DJANGO_DB_NAME: securedropdb
      DJANGO_DB_PASSWORD: securedroppassword
      DJANGO_DB_PORT: 5432
      DJANGO_DB_USER: securedrop
      DJANGO_ONION_HOSTNAME: secrdrop5wyphb5x.onion
      DJANGO_XMLTEST_OUTPUT: 'yes'
      ENABLE_DEBUG_TOOLBAR:
    working_dir: /django
    userns_mode: keep-id
    volumes:
      - ./:/django:z
    ports:
      - '127.0.0.1:8000:8000'
    healthcheck:
      test:
        ['CMD', 'curl', '--fail', 'http://localhost:8000/health/ok/?monitor']
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 45s
    networks:
      app:
        aliases:
          - app
