---
networks:
  app:
services:
  postgresql:
    image: postgres:14
    ports:
      - '5432:5432'
    volumes:
      - ./:/django:ro
    environment:
      POSTGRES_PASSWORD: securedroppassword
      POSTGRES_USER: securedrop
      POSTGRES_DB: securedropdb
    user: postgres
    networks:
      app:
        aliases:
          - db

  node:
    build:
      context: .
      dockerfile: devops/docker/NodeDockerfile
      args:
        USERID: ${UID:?err}
    image: localhost/securedroporg-node
    volumes:
      - ./:/django:z
    working_dir: /django
    user: ${UID:?err}
    healthcheck:
      test: jq '.status' webpack-stats.json |grep -q -e compiling -e error -e done
      interval: 10s
      start_period: 1m30s
    userns_mode: keep-id
    networks:
      - app

  django:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: devops/docker/DevDjangoDockerfile
      args:
        USERID: ${UID:?err}
    image: localhost/securedroporg-django
    depends_on:
      postgresql:
        condition: service_healthy
      node:
        condition: service_healthy
    environment:
      DJANGO_DB_PASSWORD: securedroppassword
      DJANGO_DB_USER: securedrop
      DJANGO_DB_NAME: securedropdb
      DJANGO_DB_PORT: 5432
      DJANGO_DB_HOST: db
      DJANGO_XMLTEST_OUTPUT: 'yes'
      DEPLOY_ENV: dev
      DJANGO_ONION_HOSTNAME: secrdrop5wyphb5x.onion
      ENABLE_DEBUG_TOOLBAR:
    working_dir: /django
    userns_mode: keep-id
    volumes:
      - ./:/django:z
    ports:
      - '127.0.0.1:8000:8000'
    healthcheck:
      test:
        ['CMD', 'curl', '--fail', 'http://localhost:8000/health/ok/?monitor']
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 45s
    networks:
      app:
        aliases:
          - app
