# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 20:01
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtailmetadata.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('directory', '0001_initial'),
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.BooleanField()),
                ('result_last_seen', models.DateTimeField(auto_now_add=True)),
                ('forces_https', models.NullBooleanField()),
                ('hsts', models.NullBooleanField()),
                ('hsts_max_age', models.IntegerField(blank=True, null=True)),
                ('hsts_entire_domain', models.NullBooleanField()),
                ('hsts_preloaded', models.NullBooleanField()),
                ('http_status_200_ok', models.NullBooleanField()),
                ('http_no_redirect', models.NullBooleanField()),
                ('expected_encoding', models.NullBooleanField()),
                ('no_server_info', models.NullBooleanField()),
                ('no_server_version', models.NullBooleanField()),
                ('csp_origin_only', models.NullBooleanField()),
                ('mime_sniffing_blocked', models.NullBooleanField()),
                ('noopen_download', models.NullBooleanField()),
                ('xss_protection', models.NullBooleanField()),
                ('clickjacking_protection', models.NullBooleanField()),
                ('good_cross_domain_policy', models.NullBooleanField()),
                ('http_1_0_caching_disabled', models.NullBooleanField()),
                ('cache_control_set', models.NullBooleanField()),
                ('cache_control_revalidate_set', models.NullBooleanField()),
                ('cache_control_nocache_set', models.NullBooleanField()),
                ('cache_control_notransform_set', models.NullBooleanField()),
                ('cache_control_nostore_set', models.NullBooleanField()),
                ('cache_control_private_set', models.NullBooleanField()),
                ('expires_set', models.NullBooleanField()),
                ('safe_onion_address', models.NullBooleanField()),
                ('no_cdn', models.NullBooleanField()),
                ('no_analytics', models.NullBooleanField()),
                ('subdomain', models.NullBooleanField()),
                ('no_cookies', models.NullBooleanField()),
                ('grade', models.CharField(default='?', editable=False, max_length=2)),
            ],
            options={
                'get_latest_by': 'result_last_seen',
            },
        ),
        migrations.CreateModel(
            name='SecuredropOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecuredropPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('landing_page_domain', models.URLField(max_length=255, unique=True, verbose_name='Landing Page Domain Name')),
                ('onion_address', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(regex='\\.onion$')], verbose_name='SecureDrop Onion Address')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('organization_description', models.CharField(blank=True, help_text='A micro description of your organization that will be displayed in the directory.', max_length=95, null=True)),
                ('countries', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='countries', to='directory.Country', verbose_name='Countries')),
                ('languages', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='languages', to='directory.Language', verbose_name='Languages Accepted')),
                ('organization_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.CustomImage')),
                ('search_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.CustomImage')),
                ('topics', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='topics', to='directory.Topic', verbose_name='Preferred Topics')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtailmetadata.models.MetadataMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.AddField(
            model_name='securedropowner',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='landing_page_checker.SecuredropPage'),
        ),
        migrations.AddField(
            model_name='result',
            name='securedrop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='landing_page_checker.SecuredropPage'),
        ),
    ]
