# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page_checker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='hsts_max_age',
            field=models.NullBooleanField(),
        ),
    ]
