# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 16:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page_checker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securedroppage',
            name='onion_address',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid .onion address.', regex='\\.onion$')], verbose_name='SecureDrop Onion Address'),
        ),
    ]
