# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page_checker', '0002_securedrop_inherits_from_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securedroppage',
            name='page',
        ),
    ]
