# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 15:37
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page_checker', '0003_remove_securedroppage_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='securedroppage',
            name='organization_description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
    ]
