# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 22:38
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page_checker', '0003_auto_20171103_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='securedrop',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='landing_page_checker.SecuredropPage'),
        ),
    ]
