# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_merge_20171117_1652'),
        ('landing_page_checker', '0004_auto_20171106_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='securedroppage',
            name='organization_logo_homepage',
            field=models.ForeignKey(blank=True, help_text='Optional second logo optimized to show up on dark backgrounds. For instances that are featured on the homepage.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.CustomImage'),
        ),
    ]
