# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_update_footer'),
        ('landing_page_checker', '0004_securedroppage_organization_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='securedroppage',
            name='organization_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.CustomImage'),
        ),
    ]
