# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 20:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page_checker', '0005_securedroppage_organization_logo_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='landing_page_domain',
            field=models.URLField(db_index=True, default='', max_length=255, verbose_name='Landing page domain name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='securedroppage',
            name='landing_page_domain',
            field=models.URLField(max_length=255, unique=True, verbose_name='Landing page domain name'),
        ),
        migrations.AlterField(
            model_name='securedroppage',
            name='languages',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='languages', to='directory.Language', verbose_name='Languages accepted'),
        ),
        migrations.AlterField(
            model_name='securedroppage',
            name='onion_address',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid .onion address.', regex='\\.onion$')], verbose_name='SecureDrop onion address'),
        ),
        migrations.AlterField(
            model_name='securedroppage',
            name='topics',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='topics', to='directory.Topic', verbose_name='Preferred topics'),
        ),
    ]
