# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 20:10
from __future__ import unicode_literals

from django.db import migrations


def copy_landing_page_domain(apps, schema_editor):
    SecuredropPage = apps.get_model('landing_page_checker', 'SecuredropPage')
    for page in SecuredropPage.objects.all():
        page.results.update(landing_page_domain=page.landing_page_domain)


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page_checker', '0006_auto_20171120_2009'),
    ]

    operations = [
        migrations.RunPython(copy_landing_page_domain, migrations.RunPython.noop)
    ]
