# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 17:59
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0010_baseitem_country_language_topic'),
        ('landing_page_checker', '0007_securedroppage_search_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='securedroppage',
            name='countries',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='countries', to='directory.Country', verbose_name='Countries'),
        ),
        migrations.AddField(
            model_name='securedroppage',
            name='languages',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='languages', to='directory.Language', verbose_name='Languages Accepted'),
        ),
        migrations.AddField(
            model_name='securedroppage',
            name='topics',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='topics', to='directory.Topic', verbose_name='Preferred Topics'),
        ),
    ]
