# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 20:26
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page_checker', '0007_copy_landing_page_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='securedrop',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='landing_page_checker.SecuredropPage'),
        ),
    ]
