# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 14:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page_checker', '0008_add_fields_to_securedroppage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securedroppage',
            name='landing_page_domain',
            field=models.URLField(max_length=255, unique=True, verbose_name='Landing Page Domain Name'),
        ),
        migrations.AlterField(
            model_name='securedroppage',
            name='onion_address',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(regex='\\.onion$')], verbose_name='SecureDrop Onion Address'),
        ),
        migrations.AlterField(
            model_name='securedroppage',
            name='organization_description',
            field=models.CharField(blank=True, help_text='A micro description of your organization that will be displayed in the directory.', max_length=95, null=True),
        ),
        migrations.AlterField(
            model_name='securedroppage',
            name='organization_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.CustomImage', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['tiff', 'ftc', 'jpc', 'grib', 'dds', 'jpf', 'png', 'mpo', 'emf', 'im', 'xbm', 'ps', 'rgb', 'h5', 'pxr', 'psd', 'ico', 'jp2', 'pgm', 'bw', 'gif', 'jpg', 'webp', 'jpx', 'pcd', 'rgba', 'wmf', 'palm', 'mic', 'ppm', 'xpm', 'icns', 'fpx', 'dcx', 'bufr', 'j2k', 'flc', 'jpeg', 'gbr', 'mpg', 'tga', 'msp', 'ras', 'tif', 'eps', 'bmp', 'jpe', 'jfif', 'pcx', 'fit', 'cur', 'iim', 'hdf', 'j2c', 'sgi', 'ftu', 'mpeg', 'pdf', 'fits', 'fli', 'pbm'])]),
        ),
    ]
