# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-10 15:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page_checker', '0009_auto_20180321_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securedroppage',
            name='onion_address',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Enter a valid .onion address.', regex='\\.onion$')], verbose_name='SecureDrop onion address'),
        ),
    ]
