# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 14:29
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landing_page_checker', '0009_add_validations_to_securedroppage'),
    ]

    operations = [
        migrations.AddField(
            model_name='securedroppage',
            name='owners',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='securedroppage',
            name='organization_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.CustomImage', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['icns', 'xbm', 'fit', 'jpc', 'dds', 'hdf', 'fli', 'gif', 'palm', 'ftc', 'mpeg', 'jpg', 'xpm', 'psd', 'jpx', 'wmf', 'cur', 'im', 'rgb', 'ras', 'fits', 'bw', 'ppm', 'jp2', 'grib', 'iim', 'h5', 'ftu', 'rgba', 'flc', 'bmp', 'gbr', 'pgm', 'emf', 'eps', 'webp', 'jpe', 'pdf', 'jpeg', 'j2c', 'tga', 'sgi', 'tif', 'dcx', 'ps', 'msp', 'png', 'pcx', 'fpx', 'pbm', 'jpf', 'jfif', 'pxr', 'ico', 'tiff', 'mpg', 'j2k', 'mic', 'mpo', 'pcd', 'bufr'])]),
        ),
    ]
