# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 15:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landing_page_checker', '0011_auto_20171019_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuredropOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='securedroppage',
            name='owners',
        ),
        migrations.AddField(
            model_name='securedropowner',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='landing_page_checker.SecuredropPage'),
        ),
    ]
