# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20171103_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footersettings',
            name='donation_link',
        ),
        migrations.AddField(
            model_name='footersettings',
            name='donation_url',
            field=models.URLField(default='https://freedom.press/crowdfunding/securedrop/'),
            preserve_default=False,
        ),
    ]
