# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('common', '0003_auto_20171108_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorAuthSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_form_text', wagtail.wagtailcore.fields.RichTextField(blank=True, default='Note: two-factor authentication is required to use your account.  After you complete this form, you must also complete setup of a two-factor authentication device.', help_text='Message displayed on the signup page', null=True)),
                ('authenticate_text', wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Message displayed on the 2FA authentication form, where the user must enter their token', null=True)),
                ('setup_text', wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Message displayed on the 2FA setup form', null=True)),
                ('backup_tokens_text', wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Message displayed on the 2FA backup tokens generation form', null=True)),
                ('remove_text', wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Message displayed on the 2FA removal form', null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
