# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 18:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20171108_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='securedrop_onion_address',
            field=models.CharField(default='secrdrop5wyphb5x.onion', max_length=255, validators=[django.core.validators.RegexValidator(message='Enter a valid .onion address.', regex='\\.onion$')], verbose_name='SecureDrop Onion Address'),
        ),
    ]
