# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('common', '0004_footersettings_securedrop_onion_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorysettings',
            name='new_instance_alert_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', help_text='Users in this group will get an email alert when a new SecureDrop instance is submitted'),
        ),
    ]
