# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_twofactorauthsettings'),
        ('common', '0004_footersettings_securedrop_onion_address'),
    ]

    operations = [
    ]
