# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('menus', '0001_initial'),
        ('common', '0004_auto_20170908_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footersettings',
            old_name='menu',
            new_name='main_menu',
        ),
        migrations.RenameField(
            model_name='footersettings',
            old_name='body',
            new_name='title',
        ),
        migrations.AddField(
            model_name='footersettings',
            name='contribute_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='donation_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='release_key',
            field=models.CharField(default='Key is unavailable', max_length=255),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='release_key_description',
            field=models.CharField(default='SecureDrop Release Signing Key \n (Not for communication)', max_length=255),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='release_key_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='support_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='menus.Menu'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='support_title',
            field=models.CharField(default='Get Support', max_length=100),
        ),
    ]
