# Generated by Django 2.2.14 on 2020-08-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20200624_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='toralertsettings',
            name='mobile_subtitle',
            field=models.CharField(blank=True, default='For security reasons we discourage use of mobile browser.', max_length=255, null=True),
        ),
    ]
