# Generated by Django 2.2.14 on 2020-10-14 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20200810_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footersettings',
            name='securedrop_onion_address',
        ),
    ]
