# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_merge_20171116_1446'),
        ('common', '0005_directorysettings_new_instance_alert_group'),
    ]

    operations = [
    ]
