# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 21:21
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings


def change_site(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    site, created = Site.objects.get_or_create(id=settings.SITE_ID)
    site.domain = 'securedrop.org'
    site.name = 'SecureDrop'
    site.save()


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_merge_20171117_1652'),
        ('sites', '__latest__'),
    ]

    operations = [
        migrations.RunPython(change_site, reverse_code=migrations.RunPython.noop),
    ]
