# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alertsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertsettings',
            name='close_text',
            field=models.CharField(default='Close Alert', help_text='Text on the close button visible only to screenreaders.', max_length=100),
        ),
    ]
