# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('common', '0007_alertsettings_close_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landing_page_link_text', models.CharField(default='Securedrop landing page', max_length=255)),
                ('compare_onion_address_text', models.CharField(default='Check this address against the one on the landing page:', help_text='Text displayed immedieately before the onion address.', max_length=255)),
                ('grade_text', models.CharField(default='Security Grade', max_length=100)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'Directory Settings',
            },
        ),
    ]
