# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-08 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20171117_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorysettings',
            name='allow_directory_management',
            field=models.BooleanField(default=False, help_text='Allow directory instance submission/management by site visitors'),
        ),
        migrations.AddField(
            model_name='directorysettings',
            name='show_scan_results',
            field=models.BooleanField(default=False, help_text='Show directory instance scan results on public site'),
        ),
    ]
