# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 20:23
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_directorysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorysettings',
            name='security_warning',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Warning displayed for sources on instance pages.', null=True),
        ),
    ]
