# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-21 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('common', '0009_auto_20180321_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorysettings',
            name='contact_email',
            field=models.EmailField(default='securedrop@freedom.press', help_text='People should contact this email address about inaccuracies or potential attacks in the directory', max_length=254),
        ),
        migrations.AddField(
            model_name='directorysettings',
            name='contact_gpg',
            field=models.ForeignKey(blank=True, help_text='Public key for email communication', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document', verbose_name='Contact email GPG'),
        ),
    ]
