# Generated by Django 4.2.26 on 2026-01-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0010_customimage_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="footersettings",
            name="bluesky_url",
            field=models.URLField(blank=True, help_text="Link to Bluesky profile"),
        ),
    ]
