# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('common', '0010_directorysettings_no_results_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='TorAlertSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Have a document to share?', max_length=255)),
                ('subtitle', models.CharField(blank=True, default='Your security is compromised while using this browser.', max_length=255, null=True)),
                ('body', wagtail.wagtailcore.fields.RichTextField(blank=True, null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
