# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 18:30
from __future__ import unicode_literals

from django.db import migrations


def update_contenttypes(apps, schema_migration):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ContentType.objects.filter(
        app_label='common',
        model='directorysettings'
    ).update(app_label='directory')


def update_contenttypes_reverse(apps, schema_migration):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ContentType.objects.filter(
        app_label='directory',
        model='directorysettings'
    ).update(app_label='common')


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20180321_1927'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    database_operations = [
        migrations.AlterModelTable('DirectorySettings', 'directory_directorysettings'),
        migrations.RunPython(update_contenttypes, update_contenttypes_reverse),
    ]

    state_operations = [
        migrations.DeleteModel('DirectorySettings'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations
        )
    ]
