# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_toralertsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='toralertsettings',
            name='tor_settings_body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='toralertsettings',
            name='tor_settings_subtitle',
            field=models.CharField(blank=True, default='These settings allow JavaScript to run which compromises your security.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='toralertsettings',
            name='tor_settings_title',
            field=models.CharField(default='Your Tor security settings are too low.', max_length=255),
        ),
    ]
