# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20171013_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toralertsettings',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Text explaining how and why to use Tor browser. Only displayed if user is not browsing with Tor.', null=True),
        ),
        migrations.AlterField(
            model_name='toralertsettings',
            name='title',
            field=models.CharField(default='Have a document to share?', help_text='Displayed if user is not browsing with Tor.', max_length=255),
        ),
        migrations.AlterField(
            model_name='toralertsettings',
            name='tor_settings_body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Text explaining how and why to change Tor security settings.', null=True),
        ),
        migrations.AlterField(
            model_name='toralertsettings',
            name='tor_settings_title',
            field=models.CharField(default='Your Tor security settings are too low. Only displayed if user is browsing with Tor already.', max_length=255),
        ),
    ]
