# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_toralertsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toralertsettings',
            name='tor_settings_title',
            field=models.CharField(default='Your Tor security settings are too low.', help_text='This alert is only displayed if the user is browsing with Tor already.', max_length=255),
        ),
    ]
