# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_orderedfeatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurepage',
            name='teaser_title',
            field=models.CharField(default='Teaser title', max_length=60),
            preserve_default=False,
        ),
    ]
