# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_featurepage_teaser_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedfeatures',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_order', to='marketing.FeaturePage', unique=True),
        ),
    ]
