# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-21 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_auto_20171108_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderedfeatures',
            options={},
        ),
        migrations.AlterField(
            model_name='orderedfeatures',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_order', to='marketing.FeaturePage'),
        ),
        migrations.AlterUniqueTogether(
            name='orderedfeatures',
            unique_together=set([('page', 'feature')]),
        ),
    ]
