# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-21 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_auto_20180321_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedfeatures',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_orders', to='marketing.FeaturePage'),
        ),
    ]
