# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171026_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
