# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 15:28
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_categorypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='blog.CategoryPage'),
        ),
    ]
