# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-04 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180426_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.Page'),
        ),
    ]
