# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170915_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='link_to_page_text',
            field=models.CharField(default='Read More', help_text='Text to display at the bottom of blog teasers that links to the blog page.', max_length=100),
        ),
    ]
