# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogindexpage_link_to_page_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='release_title',
            field=models.CharField(default='Current Release', help_text='Text to display as a title for the current release in the sidebar.', max_length=100),
        ),
    ]
