# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170926_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='release',
            field=models.OneToOneField(blank=True, help_text='Releases can be associated with only one post, which should be a release announcement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_page', to='github.Release'),
        ),
    ]
