# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_release_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='teaser_image',
        ),
    ]
