# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_add_metadata_mixin'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='orphans',
            field=models.PositiveIntegerField(default=5, help_text='Number of posts to append to the last page to prevent there being a small last page.'),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='per_page',
            field=models.PositiveIntegerField(default=8, help_text='Number of posts to display per page.'),
        ),
    ]
