# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20171018_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='orphans',
            field=models.PositiveIntegerField(default=5, help_text='Minimum number of stories on the last page (if the last page is smaller, they will get added to the preceding page).'),
        ),
    ]
