# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landing_page_checker', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageinstances',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='landing_page_checker.SecuredropPage'),
        ),
        migrations.AddField(
            model_name='homepageinstances',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='home.HomePage'),
        ),
    ]
