# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_add_metadata_mixin_to_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='description_header',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
