# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-21 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_auto_20171108_1523'),
        ('home', '0003_auto_20171026_2001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagefeature',
            options={},
        ),
        migrations.AlterField(
            model_name='homepagefeature',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='marketing.FeaturePage'),
        ),
        migrations.AlterUniqueTogether(
            name='homepagefeature',
            unique_together=set([('page', 'feature')]),
        ),
    ]
