# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_button'),
        ('home', '0003_add_description_fields_to_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionButtons',
            fields=[
                ('button_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.Button')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_buttons', to='home.HomePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('common.button', models.Model),
        ),
    ]
