# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180321_2029'),
    ]

    run_before = [
        ('landing_page_checker', '0013_move_securedroppage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageinstances',
            name='instance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
