# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180413_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageinstances',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='directory.SecuredropPage'),
        ),
    ]
