# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='features_header',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
