# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20170908_1724'),
        ('home', '0007_homepageinstances'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstancesButton',
            fields=[
                ('button_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.Button')),
            ],
            bases=('common.button',),
        ),
        migrations.AddField(
            model_name='homepage',
            name='instances_header',
            field=models.CharField(default='Share Documents Securely With These Organizations', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='features_header',
            field=models.CharField(default='What SecureDrop Does', max_length=255),
        ),
        migrations.AddField(
            model_name='instancesbutton',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_button', to='home.HomePage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='instances_button',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.InstancesButton'),
        ),
    ]
