# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_add_instance_button_to_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='instance_link_default_text',
            field=models.CharField(default='SecureDrop landing page', help_text='Text displayed linking to each instance landing page.', max_length=255),
        ),
    ]
