# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20170908_1724'),
        ('home', '0009_homepage_instance_link_default_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturesButton',
            fields=[
                ('button_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.Button')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='features_button', to='home.HomePage')),
            ],
            bases=('common.button',),
        ),
    ]
