# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_featuresbutton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='description_header',
            field=models.CharField(default='Share and accept documents securely.', max_length=255),
        ),
    ]
