# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_orderedfeatures'),
        ('home', '0011_change_description_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='marketing.FeaturePage')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='home.HomePage')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.RemoveField(
            model_name='feature',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='page',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
