# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_change_description_header'),
        ('landing_page_checker', '0002_securedrop_inherits_from_page')
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageinstances',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='landing_page_checker.SecuredropPage'),
        ),
    ]
