# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20171010_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagefeature',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='marketing.FeaturePage', unique=True),
        ),
    ]
