# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-19 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_auto_20170517_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='grade',
            field=models.CharField(default='?', editable=False, max_length=2),
        ),
        migrations.AlterField(
            model_name='result',
            name='hsts_max_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='securedrop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='directory.Securedrop'),
        ),
    ]
