# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_auto_20170519_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='forces_https',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='securedrop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='directory.Securedrop'),
        ),
    ]
