# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-16 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecureDrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=255, unique=True, verbose_name='Organization')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Slug')),
                ('landing_page_domain', models.CharField(help_text='Specify the domain name without the scheme, e.g. "example.com" instead of "https://example.com"', max_length=255, unique=True, verbose_name='Landing Page Domain Name')),
                ('onion_address', models.CharField(max_length=255, unique=True, verbose_name='SecureDrop Onion Address')),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
