# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-17 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.BooleanField()),
                ('result_last_seen', models.DateTimeField(auto_now_add=True)),
                ('hsts', models.NullBooleanField()),
                ('hsts_max_age', models.IntegerField(null=True)),
                ('hsts_entire_domain', models.NullBooleanField()),
                ('hsts_preloaded', models.NullBooleanField()),
                ('http_status_200_ok', models.NullBooleanField()),
                ('http_no_redirect', models.NullBooleanField()),
                ('expected_encoding', models.NullBooleanField()),
                ('no_server_info', models.NullBooleanField()),
                ('no_server_version', models.NullBooleanField()),
                ('csp_origin_only', models.NullBooleanField()),
                ('mime_sniffing_blocked', models.NullBooleanField()),
                ('noopen_download', models.NullBooleanField()),
                ('xss_protection', models.NullBooleanField()),
                ('clickjacking_protection', models.NullBooleanField()),
                ('good_cross_domain_policy', models.NullBooleanField()),
                ('http_1_0_caching_disabled', models.NullBooleanField()),
                ('cache_control_set', models.NullBooleanField()),
                ('cache_control_revalidate_set', models.NullBooleanField()),
                ('cache_control_nocache_set', models.NullBooleanField()),
                ('cache_control_notransform_set', models.NullBooleanField()),
                ('cache_control_nostore_set', models.NullBooleanField()),
                ('cache_control_private_set', models.NullBooleanField()),
                ('expires_set', models.NullBooleanField()),
                ('safe_onion_address', models.NullBooleanField()),
                ('no_cdn', models.NullBooleanField()),
                ('no_analytics', models.NullBooleanField()),
                ('no_cookies', models.NullBooleanField()),
                ('grade', models.CharField(editable=False, max_length=2)),
            ],
            options={
                'get_latest_by': 'result_last_seen',
            },
        ),
        migrations.AlterField(
            model_name='securedrop',
            name='landing_page_domain',
            field=models.CharField(max_length=255, unique=True, verbose_name='Landing Page Domain Name'),
        ),
        migrations.AddField(
            model_name='result',
            name='securedrop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='directory.Securedrop'),
        ),
    ]
