# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-17 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_auto_20170517_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='subdomain',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='securedrop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='directory.Securedrop'),
        ),
    ]
