from django.core import mail
from django.test import TestCase
from foliage.contextmanagers import page_tree

from forms.models import FormPage


class EmailPageTestCase(TestCase):

    def test_no_auto_generated_header(self):
        """
        Emails generated by a `FormPage` should not include an
        'Auto-Submitted' header

        See forms.utils.send_mail for details
        """

        PAGE_TREE = (
            FormPage(
                title='Form',
                from_address='sender@example.com',
                to_address='receiver@example.com',
                slug='form'
            ),
        )

        with page_tree(PAGE_TREE):
            self.client.post('/')  # Posting to a form page triggers an email
            self.assertNotIn('Auto-Submitted', mail.outbox[0].extra_headers)
