# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-26 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['slug'], name='menus_menu_slug_aab763_idx'),
        ),
    ]
