# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('tag_name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
