# Generated by Django 5.2.16 on 2026-07-16 14:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0003_release_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="release",
            options={"ordering": ["-date"]},
        ),
    ]
