# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchdocument',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
