# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-26 19:07
from __future__ import unicode_literals

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


def forwards(apps, schema_editor):
    "Build a new search vector for each search document"
    SearchDocument = apps.get_model('search', 'SearchDocument')
    for document in SearchDocument.objects.all():
        document.search_vector = django.contrib.postgres.search.SearchVector(
            'title', 'search_content'
        )
        document.save(update_fields=['search_vector'])


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchdocument',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='searchdocument',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='search_sear_search__b5d516_gin'),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop)
    ]
