# Generated by Django 2.2.24 on 2021-11-24 20:10

from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations


class Migration(migrations.Migration):

    run_before = [
        ('search', '0001_initial'),
    ]

    operations = [
        HStoreExtension(),
    ]
