# Generated by Django 1.11.20 on 2019-02-19 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simple", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faqpage",
            name="search_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="common.CustomImage",
                verbose_name="Search image",
            ),
        ),
        migrations.AlterField(
            model_name="simplepage",
            name="search_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="common.CustomImage",
                verbose_name="Search image",
            ),
        ),
        migrations.AlterField(
            model_name="simplepagewithmenusidebar",
            name="search_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="common.CustomImage",
                verbose_name="Search image",
            ),
        ),
    ]
