# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 19:19
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplepage',
            name='sidebar_content',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.StructBlock((('content', wagtail.wagtailcore.blocks.CharBlock()),))), ('rich_text', wagtail.wagtailcore.blocks.RichTextBlock())), blank=True, default=None),
        ),
    ]
