# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0003_change_styled_text_block_to_richtext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simplepage',
            name='sidebar_content',
        ),
    ]
