# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alertsettings_close_text'),
        ('simple', '0004_remove_simplepage_sidebar_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplepage',
            name='search_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.CustomImage'),
        ),
        migrations.AddField(
            model_name='simplepagewithmenusidebar',
            name='search_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.CustomImage'),
        ),
    ]
