---
name: Publish

on:
  push:
    branches:
      - develop
      - prod
      - experimental

permissions:
  contents: read
  actions: read

jobs:
  git-facts:
    name: Git facts
    uses: ./.github/workflows/git-facts.yaml

  build:
    name: Build
    needs: git-facts
    uses: freedomofpress/actionslib/.github/workflows/oci-build.yaml@main
    permissions:
      contents: read
      actions: read
      packages: write
    with:
      context: '.'
      containerfile: ci/containers/Containerfile
      target: prod
      # No blank lines: buildah-build passes each line on as a --build-arg.
      build-args: |
        USERID=1000
        ${{ needs.git-facts.outputs.build-args }}
      registry: ghcr.io/freedomofpress/securedrop-org
      add-branch-tags: true

  notify:
    uses: freedomofpress/actionslib/.github/workflows/update-k8s-trigger.yaml@main
    needs:
      - build
    if: ${{ needs.build.result == 'success' }}
    permissions:
      contents: read
      actions: read
      pull-requests: read
    with:
      trigger: sdo/${{ github.ref_name }}
      sha: ${{ github.sha }}
    secrets:
      local-token: ${{ secrets.GITHUB_TOKEN }}
      k8s-configs-token: ${{ secrets.K8S_CONFIGS_GITHUB_TOKEN }}
