---
name: Publish

on:
  push:
    branches:
      - develop
      - prod
      - experimental

permissions:
  contents: read
  actions: read

jobs:
  build:
    name: Build
    uses: freedomofpress/actionslib/.github/workflows/oci-build.yaml@main
    permissions:
      contents: read
      actions: read
      packages: write
    with:
      context: '.'
      containerfile: devops/docker/ProdDjangoDockerfile
      build-args: USERID=1000
      requires-deep-history: true
      registry: ghcr.io/freedomofpress/securedrop-org
      add-branch-tags: true

  notify:
    uses: freedomofpress/actionslib/.github/workflows/update-k8s-trigger.yaml@main
    needs:
    - build
    if: ${{ needs.build.result == 'success' }}
    permissions:
      contents: read
      actions: read
      pull-requests: read
    with:
      trigger: sdo/${{ github.ref_name }}
      sha: ${{ github.sha }}
    secrets:
      local-token: ${{ secrets.GITHUB_TOKEN }}
      k8s-configs-token: ${{ secrets.K8S_CONFIGS_GITHUB_TOKEN }}

