# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securedropinstance',
            name='page',
        ),
        migrations.DeleteModel(
            name='SecureDropInstance',
        ),
    ]
