# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securedropinstance',
            name='tor_address',
        ),
        migrations.RemoveField(
            model_name='securedropinstance',
            name='url',
        ),
        migrations.AddField(
            model_name='securedropinstance',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securedropinstance',
            name='landing_page',
            field=models.URLField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securedropinstance',
            name='onion_address',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securedropinstance',
            name='organization',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securedropinstance',
            name='slug',
            field=models.SlugField(default='', editable=False, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
