# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_directorypage_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directorypage',
            name='thank_you_text',
        ),
        migrations.RemoveField(
            model_name='directorypage',
            name='thank_you_title',
        ),
    ]
