# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 20:20
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_directorypage_search_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorypage',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
    ]
