# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-22 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_auto_20180501_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='directoryentry',
            name='delisted',
            field=models.CharField(blank=True, choices=[('http', 'Mixed-content or no HTTPS'), ('no200', 'Non-200 status response'), ('other', 'Other')], default=None, help_text='If set, entry will not show up in the directory, but the page will still be live. Should be used for SecureDrop instances that are under review for detected issues.', max_length=10, null=True),
        ),
    ]
