# -*- coding: utf-8 -*-
"""
This migrations _only_ creates the SecuredropOwner model in the migration
state, not in the database. The model is created in the database by moving the
table from the landing_page_checker app in landing_page_checker
migration 0011_move_results_model
"""

# Generated by Django 1.11.11 on 2018-04-12 21:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page_checker', '0012_move_securedrop_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '0004_create_result'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='SecuredropOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to=settings.AUTH_USER_MODEL)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='landing_page_checker.SecuredropPage')),
            ],
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
