# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_directorypage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorypage',
            name='source_warning',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='A warning for sources about checking onion addresses.', null=True),
        ),
        migrations.AddField(
            model_name='directorypage',
            name='submit_body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directorypage',
            name='submit_title',
            field=models.CharField(default='Want to get your instance listed?', max_length=255),
        ),
    ]
