# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_securedropowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='securedrop',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='securedropowner',
            name='page',
            field=models.PositiveIntegerField(),
        ),
    ]
