# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-28 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_directoryentry_delisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='no_referrer_policy_set',
            field=models.NullBooleanField(),
        ),
    ]
