# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_add_sidebar_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorypage',
            name='submit_button_text',
            field=models.CharField(default='Scan my instance', help_text='Text displayed on link to scanning form.', max_length=100),
        ),
    ]
