# -*- coding: utf-8 -*-
"""
This migration _only_ creates the SecuredropPage model in the migration
state, not in the database. The model is created in the database by moving the
table from the landing_page_checker app in landing_page_checker
migration 0013_move_securedroppage
"""

# Generated by Django 1.11.11 on 2018-04-13 17:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtailmetadata.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('common', '0010_auto_20180321_1927'),
        ('directory', '0006_auto_20180413_1644'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='SecuredropPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('landing_page_domain', models.URLField(max_length=255, unique=True, verbose_name='Landing page domain name')),
                ('onion_address', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Enter a valid .onion address.', regex='\\.onion$')], verbose_name='SecureDrop onion address')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('organization_description', models.CharField(blank=True, help_text='A micro description of your organization that will be displayed in the directory.', max_length=95, null=True)),
                ('countries', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='countries', to='directory.Country', verbose_name='Countries')),
                ('languages', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='languages', to='directory.Language', verbose_name='Languages accepted')),
                ('organization_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.CustomImage')),
                ('organization_logo_homepage', models.ForeignKey(blank=True, help_text='Optional second logo optimized to show up on dark backgrounds. For instances that are featured on the homepage.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.CustomImage')),
                ('search_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.CustomImage')),
                ('topics', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='topics', to='directory.Topic', verbose_name='Preferred topics')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtailmetadata.models.MetadataMixin, 'wagtailcore.page', models.Model),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
    ]
