# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('directory', '0006_directorypage_submit_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorypage',
            name='faq_link',
            field=models.ForeignKey(blank=True, help_text="Linked to by the info icon next to 'Security' in the directory table headers.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
