# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-28 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_scanresult_no_referrer_policy_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanresult',
            old_name='no_referrer_policy_set',
            new_name='referrer_policy_set_to_no_referrer',
        ),
    ]
