# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 17:29
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_securedroppage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='securedrop',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='directory.SecuredropPage'),
        ),
        migrations.AlterField(
            model_name='securedropowner',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='directory.SecuredropPage'),
        ),
    ]
