# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 18:57
from __future__ import unicode_literals

import directory.models.entry
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_directoryentry_warnings_ignored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directoryentry',
            name='warnings_ignored',
            field=directory.models.entry.ChoiceArrayField(base_field=models.CharField(choices=[('no_cookies', 'Use of Cookies'), ('no_cdn', 'Use of CDN'), ('no_analytics', 'Use of Analytics'), ('subdomain', 'Subdomain'), ('referrer_policy_set_to_no_referrer', 'Referer Policy'), ('safe_onion_address', 'Links to Onion Addresses')], max_length=50), blank=True, default=[], help_text='Landing page warnings that will not be shown to someone viewing this entry, even if they are in the scan results. Select multiples with shift or control click.', size=None),
        ),
    ]
