# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_auto_20180918_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='redirect_target',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Final destination of redirects from the landing page url'),
        ),
    ]
