# -*- coding: utf-8 -*-
"""
This migration _only_ creates the DirectorySettings model in the migration
state, not in the database. The model is created in the database by moving the
table from the common app in common migration 0011_move_directorysettings
"""

# Generated by Django 1.11.11 on 2018-04-13 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_move_directorysettings'),
        ('wagtaildocs', '0007_merge'),
        ('auth', '0008_alter_user_username_max_length'),
        ('wagtailcore', '0040_page_draft_title'),
        ('directory', '0008_auto_20180413_1729'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='DirectorySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(default='securedrop@freedom.press', help_text='People should contact this email address about inaccuracies or potential attacks in the directory', max_length=254)),
                ('grade_text', models.CharField(default='Security Grade', max_length=100)),
                ('no_results_text', wagtail.wagtailcore.fields.RichTextField(default='Results could not be calculated.', help_text='Text displayed when there are no results for a results group.')),
                ('allow_directory_management', models.BooleanField(default=False, help_text='Allow directory instance submission/management by site visitors')),
                ('show_scan_results', models.BooleanField(default=False, help_text='Show directory instance scan results on public site')),
                ('contact_gpg', models.ForeignKey(blank=True, help_text='Public key for email communication', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document', verbose_name='Contact email GPG')),
                ('new_instance_alert_group', models.OneToOneField(blank=True, help_text='Users in this group will get an email alert when a new SecureDrop instance is submitted', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'Directory Settings',
            },
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
