# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_resultgroup_resultstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorypage',
            name='submit_button_text',
            field=models.CharField(default='Get Started', help_text='Text displayed on link to scanning form.', max_length=100),
        ),
    ]
