# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_auto_20171011_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='directory.BaseItem')),
            ],
            options={
                'abstract': False,
            },
            bases=('directory.baseitem',),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='directory.BaseItem')),
            ],
            options={
                'abstract': False,
            },
            bases=('directory.baseitem',),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='directory.BaseItem')),
            ],
            options={
                'abstract': False,
            },
            bases=('directory.baseitem',),
        ),
    ]
