# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_directorysettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SecuredropPage',
            new_name='DirectoryEntry',
        ),
    ]
