# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_scanresult_redirect_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='no_cross_domain_redirects',
            field=models.NullBooleanField(),
        ),
    ]
