# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 14:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0010_baseitem_country_language_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorypage',
            name='orphans',
            field=models.PositiveSmallIntegerField(default=2, help_text='Minimum number of stories on the last page (if the last page is smaller, they will get added to the preceding page)', validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='directorypage',
            name='per_page',
            field=models.PositiveSmallIntegerField(default=10, help_text='Number of news stories to display per page', validators=[django.core.validators.MaxValueValidator(25)]),
        ),
    ]
