# Generated by Django 1.11.15 on 2018-09-24 15:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("directory", "0010_scanresult_no_cross_domain_redirects"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scanresult",
            name="http_no_redirect",
        ),
    ]
