# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0010_auto_20180413_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='landing_page_domain',
            new_name='landing_page_url',
        ),
        migrations.RenameField(
            model_name='directoryentry',
            old_name='landing_page_domain',
            new_name='landing_page_url',
        ),
    ]
