# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0011_auto_20180413_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directoryentry',
            name='landing_page_url',
            field=models.URLField(max_length=255, unique=True, verbose_name='Landing page URL'),
        ),
        migrations.AlterField(
            model_name='result',
            name='landing_page_url',
            field=models.URLField(db_index=True, max_length=255, verbose_name='Landing page URL'),
        ),
    ]
