# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0011_add_pagination_fields_to_directorypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorypage',
            name='org_details_form_text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directorypage',
            name='org_details_form_title',
            field=models.CharField(default='Enter organization details', max_length=100),
        ),
        migrations.AddField(
            model_name='directorypage',
            name='scanner_form_text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directorypage',
            name='scanner_form_title',
            field=models.CharField(default='Scan', max_length=100),
        ),
    ]
