# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-16 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0011_remove_scanresult_http_no_redirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='cross_domain_asset_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='no_cross_domain_assets',
            field=models.NullBooleanField(),
        ),
    ]
