# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-19 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0012_auto_20181016_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='ignored_cross_domain_assets',
            field=models.TextField(blank=True, default=''),
        ),
    ]
