# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0012_auto_20171023_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorypage',
            name='thank_you_text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directorypage',
            name='thank_you_title',
            field=models.CharField(default='Thank you', max_length=100),
        ),
    ]
