# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-18 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0012_auto_20180416_1416'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Result',
            new_name='ScanResult',
        ),
        migrations.AlterField(
            model_name='resultstate',
            name='name',
            field=models.CharField(help_text='Must be a field in the directory.ScanResult model.', max_length=255),
        ),
    ]
