# Generated by Django 1.11.15 on 2018-11-21 22:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("directory", "0013_auto_20181119_2255"),
        ("directory", "0013_auto_20181121_2145"),
    ]

    operations = []
