# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0013_auto_20180418_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemporaryLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemporaryTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='temporary_countries',
            field=models.ManyToManyField(blank=True, related_name='countries', to='directory.TemporaryCountry', verbose_name='Countries'),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='temporary_languages',
            field=models.ManyToManyField(blank=True, related_name='languages', to='directory.TemporaryLanguage', verbose_name='Languages accepted'),
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='temporary_topics',
            field=models.ManyToManyField(blank=True, related_name='topics', to='directory.TemporaryTopic', verbose_name='Preferred topics'),
        ),
    ]
