# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0013_auto_20171023_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorypage',
            name='manage_instances_text',
            field=models.CharField(default='Manage instances', help_text='Text displayed on link to user dashboard.', max_length=100),
        ),
    ]
