# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0015_migrate_taxonomies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='baseitem_ptr',
        ),
        migrations.RemoveField(
            model_name='language',
            name='baseitem_ptr',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='baseitem_ptr',
        ),
        migrations.RemoveField(
            model_name='directoryentry',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='directoryentry',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='directoryentry',
            name='topics',
        ),
        migrations.DeleteModel(
            name='BaseItem',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
