# Generated by Django 2.1.7 on 2019-03-05 17:26

import directory.models.entry
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0016_auto_20190219_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directoryentry',
            name='permitted_domains_for_assets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='Comma-separated list of additional domains that will not trigger the cross domain asset warning for this landing page.  Subdomains on domains in this list are ignored.  For example, adding "news.bbc.co.uk" permits all assets from "bbc.co.uk".', size=None),
        ),
        migrations.AlterField(
            model_name='directoryentry',
            name='warnings_ignored',
            field=directory.models.entry.ChoiceArrayField(base_field=models.CharField(choices=[('no_cdn', 'Use of CDN'), ('no_third_party_assets', 'Use of analytics or third party assets'), ('subdomain', 'Subdomain'), ('referrer_policy_set_to_no_referrer', 'Referer Policy'), ('safe_onion_address', 'Links to Onion Addresses')], max_length=50), blank=True, default=list, help_text='Landing page warnings that will not be shown to someone viewing this entry, even if they are in the scan results. Select multiples with shift or control click.', size=None),
        ),
    ]
