# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0016_delete_old_taxonomies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TemporaryLanguage',
            new_name='Language',
        ),
        migrations.RenameModel(
            old_name='TemporaryTopic',
            new_name='Topic',
        ),
        migrations.RenameModel(
            old_name='TemporaryCountry',
            new_name='Country',
        ),
    ]
