# Generated by Django 2.2.10 on 2020-03-30 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_customimage_file_hash'),
        ('directory', '0017_auto_20190305_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='directoryentry',
            name='organization_logo_square',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.CustomImage'),
        ),
    ]
