# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 16:33
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0018_rename_taxonomies_fieldsy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directoryentry',
            name='countries',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='countries', to='directory.Country', verbose_name='Countries'),
        ),
        migrations.AlterField(
            model_name='directoryentry',
            name='languages',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='languages', to='directory.Language', verbose_name='Languages accepted'),
        ),
        migrations.AlterField(
            model_name='directoryentry',
            name='topics',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='topics', to='directory.Topic', verbose_name='Preferred topics'),
        ),
    ]
