# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-20 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('directory', '0019_convert_taxonomies_to_pm2m'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AddField(
            model_name='directorypage',
            name='directory_submission_form',
            field=models.ForeignKey(blank=True, help_text='If directory self-management tools are enabled in Directory Settings, this will have no effect. Otherwise this should be a link to a FormPage where SecureDrop admins can submit their instance to the directory', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
