# Generated by Django 2.2.12 on 2020-08-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0019_directorysettings_report_error_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directoryentry',
            name='delisted',
            field=models.CharField(blank=True, choices=[('http', 'Mixed-content or no HTTPS'), ('no200', 'Non-200 status response'), ('down', 'Extended downtime'), ('other', 'Other')], default=None, help_text='If set, entry will not show up in the directory, but the page will still be live. Should be used for SecureDrop instances that are under review for detected issues.', max_length=10, null=True),
        ),
    ]
