# Generated by Django 2.2.10 on 2020-09-03 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0020_directoryentry_organization_url'),
        ('directory', '0020_auto_20200820_1531'),
    ]

    operations = [
    ]
