# Generated by Django 3.2.13 on 2022-06-01 16:35

import directory.models.entry
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0026_directoryentry_warnings_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directoryentry',
            name='warnings_ignored',
            field=directory.models.entry.ChoiceArrayField(base_field=models.CharField(choices=[('unreachable_landing_page', 'Landing Page Unreachable'), ('no_third_party_assets', 'Use of analytics or third party assets'), ('subdomain', 'Subdomain'), ('referrer_policy_set_to_no_referrer', 'Referer Policy'), ('safe_onion_address', 'Links to Onion Addresses')], max_length=500), blank=True, default=list, help_text='Landing page warnings that will not be shown to someone viewing this entry, even if they are in the scan results.', size=None),
        ),
        migrations.AlterField(
            model_name='directoryentry',
            name='warnings_pinned',
            field=directory.models.entry.ChoiceArrayField(base_field=models.CharField(choices=[('unreachable_landing_page', 'Landing Page Unreachable'), ('no_third_party_assets', 'Use of analytics or third party assets'), ('subdomain', 'Subdomain'), ('referrer_policy_set_to_no_referrer', 'Referer Policy'), ('safe_onion_address', 'Links to Onion Addresses')], max_length=500), blank=True, default=list, help_text='Landing page warnings that will be always be shown to someone viewing this entry, even if not reflected in the scan results.', size=None),
        ),
    ]
