# Generated by Django 5.2.15 on 2026-07-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("directory", "0028_remove_directorysettings_allow_directory_management"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directoryentry",
            name="organization_description",
            field=models.CharField(
                blank=True,
                help_text="A micro description of your organization that will be displayed in the directory.",
                max_length=255,
                null=True,
            ),
        ),
    ]
